import { FileText } from 'lucide-react';
import { useTheme } from '../hooks/useTheme';
import { FadeIn } from '../components/AnimationWrappers';
import PublicLayout from '../layouts/PublicLayout';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using MortgageAI ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, please do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.`,
  },
  {
    title: '2. Description of Service',
    content: `MortgageAI is an AI-powered mortgage advisory platform that allows users to analyze loan options, calculate EMIs, and receive personalized home loan guidance. The Service includes the website, mobile interfaces, APIs, and any related products or services offered by MortgageAI Inc.`,
  },
  {
    title: '3. User Accounts',
    content: `To access certain features, you must create an account. You are responsible for:

• Maintaining the confidentiality of your account credentials.
• All activities that occur under your account.
• Providing accurate and up-to-date information.
• Immediately notifying us of any unauthorized use of your account.

You must be at least 13 years of age to use the Service.`,
  },
  {
    title: '4. Acceptable Use',
    content: `You agree not to:

• Use the Service for any unlawful or fraudulent purpose.
• Submit content that is harmful, abusive, threatening, defamatory, or violates any third-party rights.
• Attempt to reverse engineer, decompile, or extract source code from our AI models or platform.
• Use automated tools to scrape, crawl, or overload our systems.
• Share, sell, or sublicense your account access to third parties.
• Submit deliberately false or misleading financial content to manipulate the AI.`,
  },
  {
    title: '5. Intellectual Property',
    content: `**Your Content**: You retain ownership of the financial details and queries you provide. By submitting content, you grant MortgageAI a limited, non-exclusive license to process and generate plans from your content.

**Generated Plans**: Mortgage plans and calculations generated by MortgageAI from your descriptions are provided for your personal information. Commercial use is governed by specific plan details.

**Our Property**: The MortgageAI platform, design, AI models, and brand are owned by MortgageAI Inc. and protected by applicable intellectual property laws.`,
  },
  {
    title: '6. Payment & Subscriptions',
    content: `Paid plans are billed on a monthly or annual basis. By subscribing, you authorize us to charge your payment method on a recurring basis. Subscriptions automatically renew unless cancelled before the renewal date. Refunds are available within 14 days of initial purchase if you are unsatisfied with the Service.`,
  },
  {
    title: '7. Disclaimers',
    content: `The Service is provided "as is" without warranties of any kind. MortgageAI does not guarantee that:

• The Service will be uninterrupted or error-free.
• AI-generated calculations will exactly match final bank offers.
• The Service will meet all of your financial requirements.

Financial guidance and calculations are for informational purposes and do not constitute formal financial, legal, or tax advice. Always verify with your lender before making decisions.`,
  },
  {
    title: '8. Limitation of Liability',
    content: `To the maximum extent permitted by law, MortgageAI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the Service. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: '9. Termination',
    content: `We reserve the right to suspend or terminate your account at our discretion if you violate these Terms or engage in behavior that harms the platform, other users, or our team. You may also delete your account at any time from your account settings.`,
  },
  {
    title: '10. Changes to Terms',
    content: `We may update these Terms from time to time. Material changes will be communicated via email or an in-app notice at least 14 days in advance. Continued use of the Service after changes constitutes acceptance.`,
  },
  {
    title: '11. Contact',
    content: `For questions about these Terms, contact us at:\n\nlegal@mortgageai.com\n\nMortgageAI Inc., 456 Finance Avenue, San Francisco, CA 94105`,
  },
];

export default function TermsOfService() {
  const { dark } = useTheme();

  return (
    <PublicLayout>
      <section className="pt-32 pb-16 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[400px] bg-emerald-600/10 blur-[120px] rounded-full pointer-events-none" />
        <div className="max-w-3xl mx-auto px-4 text-center relative">
          <FadeIn>
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-emerald-500 to-amber-400 flex items-center justify-center mx-auto mb-6">
              <FileText className="w-7 h-7 text-white" />
            </div>
            <h1 className={`font-display text-5xl sm:text-6xl font-bold mb-6 ${dark ? 'text-white' : 'text-slate-900'}`}>
              Terms of <span className="gradient-text">Service</span>
            </h1>
            <p className={`text-base ${dark ? 'text-slate-500' : 'text-slate-400'}`}>
              Last updated: May 10, 2026
            </p>
            <p className={`text-xl leading-relaxed mt-4 ${dark ? 'text-slate-400' : 'text-slate-600'}`}>
              Please read these terms carefully before using MortgageAI.
            </p>
          </FadeIn>
        </div>
      </section>

      <section className="pb-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-8">
            {sections.map(({ title, content }, i) => (
              <FadeIn key={title} delay={i * 0.05}>
                <div className={`p-8 rounded-2xl border ${dark ? 'bg-[#12121a] border-white/8' : 'bg-white border-slate-200 shadow-sm'}`}>
                  <h2 className={`font-display text-xl font-bold mb-4 ${dark ? 'text-white' : 'text-slate-900'}`}>{title}</h2>
                  <div className={`text-sm leading-relaxed whitespace-pre-line ${dark ? 'text-slate-400' : 'text-slate-600'}`}>
                    {content}
                  </div>
                </div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
